version: '3'
services:

  wd:
    container_name: wd
    build:
      context: .
    command: node ./dist/index.js
    environment:
      - MONGO_CONNECTION_STRING=mongodb+srv://gasame6865:dtNWMqfU@cluster0.0u67a.mongodb.net/supertest
      - JWT_SECRET=top_secret_phrase
      - PORT=8001
    ports:
      - 8001:8001
