export const INVEST_CITY_PRICE = 150;
export const INVEST_PRICE = 200;
export const DEVELOP_NUCLEAR_TECHNOLOGY_PRICE = 500;
export const IMPLEMENT_ENVIROMENTAL_PROGRAM_PRICE = 500;
export const CREATE_BOMB_PRICE = 150;
export const CREATE_SHIELD_PRICE = 300;
