name: Deploy

on:
  push:
    branches:
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "world-domination-server" #Must be unique in Heroku
          heroku_email: "dreamteam2020q3@gmail.com"
          usedocker: true
          appdir: "server"
        env:
          HD_MONGO_CONNECTION_STRING: ${{secrets.MONGO_CONNECTION_STRING}}
          HD_JWT_SECRET: ${{secrets.JWT_SECRET}}
